#PANDAS ASSIGNMENT 1(Question 1 - 25)

##Topic 1: Introduction to Pandas

1. What is Pandas? Explain its features and applications in Data Science.

Definition: Pandas is an open-source Python library built on top of NumPy, designed for flexible, high-performance data manipulation, analysis, and cleaning.

Key Features:
- Primary data structures: 1D Series and 2D tabular DataFrame.  
- Handling missing values (NaN/None) seamlessly.  
- Flexible reshaping, pivoting, slicing, indexing, and subsetting.  
- Robust I/O tools to read and write formats such as CSV, Excel, SQL, and JSON.
- Native group-by and aggregation engines for data munging.

Applications: Exploratory Data Analysis (EDA), feature engineering, time-series analysis, cleaning messy real-world datasets, and preparing data pipelines for machine learning models.

2. Import the Pandas library and explain the purpose of the alias pd.

In [108]:
import pandas as pd

Purpose of pd: pd is the globally accepted standard alias/nickname in Python data science. It reduces typing overhead (e.g., pd.DataFrame() instead of pandas.DataFrame()) and maintains code consistency across teams and open-source libraries.

##Topic 2: Series

3. Create a Series from a Python list.

In [109]:
data_list = [10, 20, 30, 40, 50]
s1 = pd.Series(data_list)
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

4. Create a Series from a NumPy array with custom indexes.

In [110]:
import numpy as np

arr = np.array([100, 200, 300])
custom_idx = ['a', 'b', 'c']
s2 = pd.Series(arr, index=custom_idx)
s2

a    100
b    200
c    300
dtype: int64

5. Create a Series from a scalar value using custom indexes.

In [111]:
s3 = pd.Series(50, index=['x', 'y', 'z'])
s3

x    50
y    50
z    50
dtype: int64

6. Create a Series containing student names as values and roll numbers as indexes.

In [112]:
students = {101: "Asha", 102: "Rahul", 103: "Kiran"}
s_students = pd.Series(students)
s_students

101     Asha
102    Rahul
103    Kiran
dtype: object

##Topic 3: DataFrame Creation

7. Create a DataFrame from a NumPy array with custom column names.

In [113]:
data_arr = np.array([[1, 2], [3, 4], [5, 6]])
df_arr = pd.DataFrame(data_arr, columns=["Col_A", "Col_B"])
df_arr

   Col_A  Col_B
0      1      2
1      3      4
2      5      6

8. Create a DataFrame from a list of dictionaries.

In [114]:
dict_list = [
    {"Name": "Asha", "Age": 21},
    {"Name": "Rahul", "Age": 22},
    {"Name": "Kiran", "Age": 20}
]
df_dict = pd.DataFrame(dict_list)
df_dict

    Name  Age
0   Asha   21
1  Rahul   22
2  Kiran   20

9. Create a DataFrame from a list of lists.

In [115]:
list_of_lists = [
    ["Laptop", 1200, 5],
    ["Mouse", 25, 20],
    ["Keyboard", 75, 15]
]
df_lists = pd.DataFrame(list_of_lists, columns=["Product", "Price", "Quantity"])
df_lists

    Product  Price  Quantity
0    Laptop   1200         5
1     Mouse     25        20
2  Keyboard     75        15

10. Create a student DataFrame containing Name, Age, Gender, City, and Marks.

In [116]:
student_data = {
    "Name": ["Asha", "Rahul", "Kiran", "Neha", "Arjun"],
    "Age": [21, 22, 20, 23, 21],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "City": ["Hyderabad", "Bangalore", "Chennai", "Mumbai", "Delhi"],
    "Marks": [85, 92, 78, 90, 88]
}
student_df = pd.DataFrame(student_data)
student_df

    Name  Age  Gender       City  Marks
0   Asha   21  Female  Hyderabad     85
1  Rahul   22    Male  Bangalore     92
2  Kiran   20    Male    Chennai     78
3   Neha   23  Female     Mumbai     90
4  Arjun   21    Male      Delhi     88

##Topic 4: Column Naming

11. Rename all the columns of the student DataFrame.

In [117]:
student_df.columns = ["Std_Name", "Std_Age", "Std_Gender", "Std_City", "Std_Marks"]
student_df

  Std_Name  Std_Age Std_Gender   Std_City  Std_Marks
0     Asha       21     Female  Hyderabad         85
1    Rahul       22       Male  Bangalore         92
2    Kiran       20       Male    Chennai         78
3     Neha       23     Female     Mumbai         90
4    Arjun       21       Male      Delhi         88

12. Rename only the Marks column to Score.

In [118]:
student_df.columns = ["Name", "Age", "Gender", "City", "Marks"]

student_df = student_df.rename(columns={"Marks": "Score"})
student_df

    Name  Age  Gender       City  Score
0   Asha   21  Female  Hyderabad     85
1  Rahul   22    Male  Bangalore     92
2  Kiran   20    Male    Chennai     78
3   Neha   23  Female     Mumbai     90
4  Arjun   21    Male      Delhi     88

##Topic 5: Reading Files

13. Load a CSV file and display the first five rows.

In [119]:
%%writefile data.csv
Name,Age,Gender,City,Marks
Asha,21,Female,Hyderabad,85
Rahul,22,Male,Bangalore,92
Kiran,20,Male,Chennai,78
Neha,23,Female,Mumbai,90
Arjun,21,Male,Delhi,88
Priya,22,Female,Pune,95
Vikram,24,Male,Kolkata,81

Writing data.csv

In [120]:
df_csv = pd.read_csv('/content/data.csv')
df_csv.head(5)

    Name  Age  Gender       City  Marks
0   Asha   21  Female  Hyderabad     85
1  Rahul   22    Male  Bangalore     92
2  Kiran   20    Male    Chennai     78
3   Neha   23  Female     Mumbai     90
4  Arjun   21    Male      Delhi     88

14. Load only the Name and Marks columns from a CSV file.

In [121]:
df_subset = pd.read_csv("data.csv", usecols=["Name", "Marks"])
df_subset.head()

    Name  Marks
0   Asha     85
1  Rahul     92
2  Kiran     78
3   Neha     90
4  Arjun     88

15. Load an Excel (.xlsx) file.

In [122]:
import pandas as pd

In [124]:
%%writefile data.xlsx
Name	Age	Gender	City	Marks
Asha	21	Female	Hyderabad	85
Rahul	22	Male	Bangalore	92
Kiran	20	Male	Chennai	78
Neha	23	Female	Mumbai	90
Arjun	21	Male	Delhi	88
Priya	22	Female	Pune	95
Vikram	24	Male	Kolkata	81

Overwriting data.xlsx

In [123]:
student_df.to_excel('/content/data.xlsx', index=False)
df_excel = pd.read_excel('/content/data.xlsx')
df_excel.head()

    Name  Age  Gender       City  Score
0   Asha   21  Female  Hyderabad     85
1  Rahul   22    Male  Bangalore     92
2  Kiran   20    Male    Chennai     78
3   Neha   23  Female     Mumbai     90
4  Arjun   21    Male      Delhi     88

16. Load a specific worksheet named Students from an Excel file.

In [147]:
student_df.to_excel("/content/students_data.xlsx", sheet_name="Students", index=False)
df_students = pd.read_excel("/content/students_data.xlsx", sheet_name="Students")
df_students.head()

    Name  Age  Gender       City  Score
0   Asha   21  Female  Hyderabad     85
1  Rahul   22    Male  Bangalore     92
2  Kiran   20    Male    Chennai     78
3   Neha   23  Female     Mumbai     90
4  Arjun   21    Male      Delhi     88

17. Write a Pandas program to save a DataFrame into an Excel (.xlsx) file.

In [126]:
student_df.to_excel("saved_students.xlsx", index=False)

18. Load a JSON file into a DataFrame.

In [127]:
%%writefile data.json
Name,Age,Gender,City,Marks
Asha,21,Female,Hyderabad,85
Rahul,22,Male,Bangalore,92
Kiran,20,Male,Chennai,78
Neha,23,Female,Mumbai,90
Arjun,21,Male,Delhi,88
Priya,22,Female,Pune,95
Vikram,24,Male,Kolkata,81

Writing data.json

In [128]:
student_df.to_json('/content/data.json', index=False)
df_excel = pd.read_json('/content/data.json')
df_excel.head()

    Name  Age  Gender       City  Score
0   Asha   21  Female  Hyderabad     85
1  Rahul   22    Male  Bangalore     92
2  Kiran   20    Male    Chennai     78
3   Neha   23  Female     Mumbai     90
4  Arjun   21    Male      Delhi     88

##Topic 6: DataFrame Inspection

19. Display the first five rows using .head() and the last five rows using .tail().

In [129]:
student_df.head(5)

    Name  Age  Gender       City  Score
0   Asha   21  Female  Hyderabad     85
1  Rahul   22    Male  Bangalore     92
2  Kiran   20    Male    Chennai     78
3   Neha   23  Female     Mumbai     90
4  Arjun   21    Male      Delhi     88

In [130]:
student_df.tail(5)

    Name  Age  Gender       City  Score
0   Asha   21  Female  Hyderabad     85
1  Rahul   22    Male  Bangalore     92
2  Kiran   20    Male    Chennai     78
3   Neha   23  Female     Mumbai     90
4  Arjun   21    Male      Delhi     88

20. Find the shape, dimensions, total elements, and datatype of the DataFrame using shape, ndim, size, and type().

In [131]:
student_df.shape

(5, 5)

In [132]:
student_df.ndim

2

In [133]:
student_df.size

25

In [134]:
type(student_df)

pandas.core.frame.DataFrame

21. Display complete information using .info() and .describe().

In [135]:
student_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Gender  5 non-null      object
 3   City    5 non-null      object
 4   Score   5 non-null      int64
dtypes: int64(2), object(3)
memory usage: 332.0+ bytes

In [136]:
student_df.describe()

             Age      Score
count   5.000000   5.000000
mean   21.400000  86.600000
std     1.140175   5.458938
min    20.000000  78.000000
25%    21.000000  85.000000
50%    21.000000  88.000000
75%    22.000000  90.000000
max    23.000000  92.000000

22. Display axes, dtypes, and empty.

In [137]:
student_df.axes

[RangeIndex(start=0, stop=5, step=1),
 Index(['Name', 'Age', 'Gender', 'City', 'Score'], dtype='object')]

In [138]:
student_df.dtypes

Name      object
Age        int64
Gender    object
City      object
Score      int64
dtype: object

In [139]:
student_df.empty

False

23. Display three random rows using .sample().

In [140]:
random_rows = student_df.sample(n=3)
random_rows

    Name  Age  Gender       City  Score
0   Asha   21  Female  Hyderabad     85
1  Rahul   22    Male  Bangalore     92
4  Arjun   21    Male      Delhi     88

24. Transpose the DataFrame using .T.

In [141]:
transposed_df = student_df.T
transposed_df

                0          1        2       3      4
Name         Asha      Rahul    Kiran    Neha  Arjun
Age            21         22       20      23     21
Gender     Female       Male     Male  Female   Male
City    Hyderabad  Bangalore  Chennai  Mumbai  Delhi
Score          85         92       78      90     88

25. Load an Excel workbook containing multiple sheets and read two different sheets using the sheet_name parameter.

In [142]:
%%writefile sheet1.csv
Name,Age,Gender,City,Marks
Asha,21,Female,Hyderabad,85
Rahul,22,Male,Bangalore,92
Kiran,20,Male,Chennai,78

Writing sheet1.csv

In [143]:
%%writefile sheet2.csv
Name,Age,Gender,City,Marks
Neha,23,Female,Mumbai,90
Arjun,21,Male,Delhi,88
Priya,22,Female,Pune,95

Writing sheet2.csv

In [154]:
df1 = pd.read_csv("sheet1.csv")
df2 = pd.read_csv("sheet2.csv")

with pd.ExcelWriter("workbook.xlsx") as writer:
    df1.to_excel(writer, sheet_name="Sheet1", index=False)
    df2.to_excel(writer, sheet_name="Sheet2", index=False)

df_sheet1 = pd.read_excel("workbook.xlsx", sheet_name="Sheet1")
df_sheet2 = pd.read_excel("workbook.xlsx", sheet_name="Sheet2")

print("--- Sheet 1 ---")
display(df_sheet1.head())

print("\n--- Sheet 2 ---")
display(df_sheet2.head())

--- Sheet 1 ---

    Name  Age  Gender       City  Marks
0   Asha   21  Female  Hyderabad     85
1  Rahul   22    Male  Bangalore     92
2  Kiran   20    Male    Chennai     78

--- Sheet 2 ---

    Name  Age  Gender    City  Marks
0   Neha   23  Female  Mumbai     90
1  Arjun   21    Male   Delhi     88
2  Priya   22  Female    Pune     95