#🐼 Pandas Task

## Dataset Creation

import pandas as pd

data = {

   "emp_id": [101, 102, 103, 104, 105],

   "name": ["Asha", "Ravi", "Kiran", "Neha", "Arjun"],

   "department": ["IT", "HR", "IT", "Finance", "HR"],

   "salary": [60000, 45000, 70000, 50000, 48000],

   "experience": [3, 2, 5, 4, 1]
   
}

df = pd.DataFrame(data)

In [60]:
import pandas as pd

data = {
    "emp_id": [101, 102, 103, 104, 105],
    "name": ["Asha", "Ravi", "Kiran", "Neha", "Arjun"],
    "department": ["IT", "HR", "IT", "Finance", "HR"],
    "salary": [60000, 45000, 70000, 50000, 48000],
    "experience": [3, 2, 5, 4, 1]
}
df = pd.DataFrame(data)

##1. .loc vs .iloc

Task 1.1

Using .loc, select employees who belong to the IT department and display only name and salary.

In [61]:
df.loc[df["department"] == "IT", ["name", "salary"]]

    name  salary
0   Asha   60000
2  Kiran   70000

Task 1.2

Using .iloc, fetch the first 3 rows and first 2 columns.

In [62]:
df.iloc[:3, :2]

   emp_id   name
0     101   Asha
1     102   Ravi
2     103  Kiran

Task 1.3

Explain why .iloc[0] works but .loc[0] may fail in some datasets.

`.iloc` uses pure integer-position indexing ($0$ to $N-1$), so `.iloc[0]` always retrieves the first row in memory regardless of the DataFrame's index. `.loc` is strictly label-based; if the DataFrame has custom labels (e.g., employee IDs or strings), or if row 0 was removed after filtering/dropping, label 0 will no longer exist in the index and will raise a KeyError.

##2. Renaming Columns

Task 2.1

Rename:

- emp_id → employee_id

- name → employee_name

In [63]:
df = df.rename(columns={"emp_id": "employee_id", "name": "employee_name"})
df

   employee_id employee_name department  salary  experience
0          101          Asha         IT   60000           3
1          102          Ravi         HR   45000           2
2          103         Kiran         IT   70000           5
3          104          Neha    Finance   50000           4
4          105         Arjun         HR   48000           1

Task 2.2

Convert all column names to uppercase.

In [64]:
df.columns = df.columns.str.upper()
df.columns

Index(['EMPLOYEE_ID', 'EMPLOYEE_NAME', 'DEPARTMENT', 'SALARY', 'EXPERIENCE'], dtype='object')

##3. Removing / Deleting Columns & Rows

Task 3.1

Remove the column bonus.

In [65]:
df = df.drop(columns=["bonus"], errors="ignore")
df

   EMPLOYEE_ID EMPLOYEE_NAME DEPARTMENT  SALARY  EXPERIENCE
0          101          Asha         IT   60000           3
1          102          Ravi         HR   45000           2
2          103         Kiran         IT   70000           5
3          104          Neha    Finance   50000           4
4          105         Arjun         HR   48000           1

Task 3.2

Delete employees whose experience is less than 2 years.

In [66]:
df = df[df["EXPERIENCE"] >= 2]
df

   EMPLOYEE_ID EMPLOYEE_NAME DEPARTMENT  SALARY  EXPERIENCE
0          101          Asha         IT   60000           3
1          102          Ravi         HR   45000           2
2          103         Kiran         IT   70000           5
3          104          Neha    Finance   50000           4

Task 3.3

Drop the row where employee_name == "Neha".

In [67]:
df = df[df["EMPLOYEE_NAME"] != "Neha"]
df

   EMPLOYEE_ID EMPLOYEE_NAME DEPARTMENT  SALARY  EXPERIENCE
0          101          Asha         IT   60000           3
1          102          Ravi         HR   45000           2
2          103         Kiran         IT   70000           5

##4. Boolean Indexing

Task 4.1
Filter employees who:
- work in HR
- AND salary > 46000

In [68]:
df[(df["DEPARTMENT"] == "HR") & (df["SALARY"] > 46000)]

Empty DataFrame
Columns: [EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT, SALARY, EXPERIENCE]
Index: []

Task 4.2
Filter employees who:
- work in IT
- OR experience ≥ 5

In [69]:
df[(df["DEPARTMENT"] == "IT") | (df["EXPERIENCE"] >= 5)]

   EMPLOYEE_ID EMPLOYEE_NAME DEPARTMENT  SALARY  EXPERIENCE
0          101          Asha         IT   60000           3
2          103         Kiran         IT   70000           5

##5. AND, OR, NOT Conditions

Task 5.1
Select employees who are:
- NOT in HR department

In [70]:
df[~(df["DEPARTMENT"] == "HR")]

   EMPLOYEE_ID EMPLOYEE_NAME DEPARTMENT  SALARY  EXPERIENCE
0          101          Asha         IT   60000           3
2          103         Kiran         IT   70000           5

Task 5.2
Select employees who:
- are NOT earning more than 60000

In [71]:
df[~(df["SALARY"] > 60000)]

   EMPLOYEE_ID EMPLOYEE_NAME DEPARTMENT  SALARY  EXPERIENCE
0          101          Asha         IT   60000           3
1          102          Ravi         HR   45000           2

##6. isin() and not in

Task 6.1
Select employees whose department is in:
- ["IT", "Finance"]

In [72]:
df[df["DEPARTMENT"].isin(["IT", "Finance"])]

   EMPLOYEE_ID EMPLOYEE_NAME DEPARTMENT  SALARY  EXPERIENCE
0          101          Asha         IT   60000           3
2          103         Kiran         IT   70000           5

Task 6.2
Select employees whose names are NOT in:
- ["Asha", "Arjun"]

In [74]:
df[~df["EMPLOYEE_NAME"].isin(["Asha", "Arjun"])]

   EMPLOYEE_ID EMPLOYEE_NAME DEPARTMENT  SALARY  EXPERIENCE
1          102          Ravi         HR   45000           2
2          103         Kiran         IT   70000           5

##7. tolist() and to_numpy()

Task 7.1

Convert the salary column into a Python list.

In [77]:
salary_list = df["SALARY"].tolist()
salary_list

[60000, 45000, 70000]

Task 7.2

Convert the entire DataFrame into a NumPy array.

In [76]:
df_array = df.to_numpy()
df_array

array([[101, 'Asha', 'IT', 60000, 3],
       [102, 'Ravi', 'HR', 45000, 2],
       [103, 'Kiran', 'IT', 70000, 5]], dtype=object)

## 8. set_index, reset_index, sort_index

Task 8.1

Set employee_id as the index.

In [79]:
df = df.set_index("EMPLOYEE_ID")
df

            EMPLOYEE_NAME DEPARTMENT  SALARY  EXPERIENCE
EMPLOYEE_ID
101                  Asha         IT   60000           3
102                  Ravi         HR   45000           2
103                 Kiran         IT   70000           5

Task 8.2

Sort the DataFrame based on the index.

In [80]:
df = df.sort_index()
df

            EMPLOYEE_NAME DEPARTMENT  SALARY  EXPERIENCE
EMPLOYEE_ID
101                  Asha         IT   60000           3
102                  Ravi         HR   45000           2
103                 Kiran         IT   70000           5

Task 8.3

Reset the index back to default and drop the old index.

In [81]:
df = df.reset_index(drop=True)
df

  EMPLOYEE_NAME DEPARTMENT  SALARY  EXPERIENCE
0          Asha         IT   60000           3
1          Ravi         HR   45000           2
2         Kiran         IT   70000           5

##9. astype()

Task 9.1

Convert:
- salary → float
- experience → string

In [82]:
df = df.astype({"SALARY": "float", "EXPERIENCE": "str"})
df

  EMPLOYEE_NAME DEPARTMENT   SALARY EXPERIENCE
0          Asha         IT  60000.0          3
1          Ravi         HR  45000.0          2
2         Kiran         IT  70000.0          5

##10. sort_values()

Task 10.1

Sort employees by:
- salary (descending)

In [83]:
df = df.sort_values(by="SALARY", ascending=False)
df

  EMPLOYEE_NAME DEPARTMENT   SALARY EXPERIENCE
2         Kiran         IT  70000.0          5
0          Asha         IT  60000.0          3
1          Ravi         HR  45000.0          2

Task 10.2

Sort employees by:
- department (ascending)
- salary (descending)

In [84]:
df = df.sort_values(by=["DEPARTMENT", "SALARY"], ascending=[True, False])
df

  EMPLOYEE_NAME DEPARTMENT   SALARY EXPERIENCE
1          Ravi         HR  45000.0          2
2         Kiran         IT  70000.0          5
0          Asha         IT  60000.0          3

## 11. drop()

Task 11.1

Drop the column experience.

In [85]:
df = df.drop(columns=["EXPERIENCE"])
df

  EMPLOYEE_NAME DEPARTMENT   SALARY
1          Ravi         HR  45000.0
2         Kiran         IT  70000.0
0          Asha         IT  60000.0

Task 11.2

Drop rows where salary < 50000 using index-based logic.

In [86]:
df = df.drop(index=df[df["SALARY"] < 50000].index)
df

  EMPLOYEE_NAME DEPARTMENT   SALARY
2         Kiran         IT  70000.0
0          Asha         IT  60000.0