#📌 Pandas CRUD Operations Workbook

##Section A: CRUD Operations on Series

Input

Subject     Marks

Math 90

Science 85

English 95

Physics 88

In [27]:
import pandas as pd
import numpy as np

Create

1) Create a Pandas Series using the given data.

In [28]:
marks_data = {"Math": 90, "Science": 85, "English": 95, "Physics": 88}
s = pd.Series(marks_data)
s

Math       90
Science    85
English    95
Physics    88
dtype: int64

Read

2) Display the marks of Science.
3) Display all subjects and their marks.

In [29]:
science_marks = s["Science"]
all_marks = s
s

Math       90
Science    85
English    95
Physics    88
dtype: int64

Update

4) Update the marks of Science.
5) Increase the marks of all subjects by 5.

In [30]:
s["Science"] = 89
s = s + 5
s

Math        95
Science     94
English    100
Physics     93
dtype: int64

Delete

6) Remove Physics from the Series.

In [31]:
s = s.drop("Physics")
s

Math        95
Science     94
English    100
dtype: int64

Analysis

7) Find the highest marks.
8) Find the lowest marks.
9) Find the average marks.
10) Count the total number of subjects.

In [112]:
s.max()

100

In [113]:
s.min()

94

In [114]:
s.mean()

np.float64(96.33333333333333)

In [115]:
s.count()

np.int64(3)

##Section B: DataFrame CRUD

Input

Emp_ID Name Salary

101 Rahul 50000

102 Priya 60000

103 Arjun 70000

Tasks

1) Create a DataFrame.
2) Display the complete DataFrame.
3) Find the shape of the DataFrame.
4) Find the size of the DataFrame.
5) Find the dimensions (ndim) of the DataFrame.
6) Display the row labels (index).
7) Display the column labels.

In [48]:
data = {
    "Emp_ID": [101, 102, 103],
    "Name": ["Rahul", "Priya", "Arjun"],
    "Salary": [50000, 60000, 70000]
}
df = pd.DataFrame(data)

In [49]:
df

   Emp_ID   Name  Salary
0     101  Rahul   50000
1     102  Priya   60000
2     103  Arjun   70000

In [50]:
df.shape

(3, 3)

In [51]:
df.size

9

In [52]:
df.ndim

2

In [53]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [54]:
df.columns

Index(['Emp_ID', 'Name', 'Salary'], dtype='object')

##Section C: Row-Level CRUD

In [55]:
df.shape

(3, 3)

Create Rows

1) Add one new employee.
2) Add multiple employee records.
3) Display the updated DataFrame.
4) Compare the DataFrame shape before and after insertion.

In [56]:
new_emp = pd.DataFrame([{"Emp_ID": 104, "Name": "Sneha", "Salary": 55000}])
df = pd.concat([df, new_emp], ignore_index=True)
df

   Emp_ID   Name  Salary
0     101  Rahul   50000
1     102  Priya   60000
2     103  Arjun   70000
3     104  Sneha   55000

In [57]:
multi_emp = pd.DataFrame([
    {"Emp_ID": 105, "Name": "Vikram", "Salary": 62000},
    {"Emp_ID": 106, "Name": "Ananya", "Salary": 48000}
])
df = pd.concat([df, multi_emp], ignore_index=True)
df

   Emp_ID    Name  Salary
0     101   Rahul   50000
1     102   Priya   60000
2     103   Arjun   70000
3     104   Sneha   55000
4     105  Vikram   62000
5     106  Ananya   48000

In [58]:
df

   Emp_ID    Name  Salary
0     101   Rahul   50000
1     102   Priya   60000
2     103   Arjun   70000
3     104   Sneha   55000
4     105  Vikram   62000
5     106  Ananya   48000

In [59]:
df.shape

(6, 3)

Read Rows
1) Display the first row.
2) Display the last row.
3) Display the first three rows.
4) Display alternate rows.
5) Display rows using .loc.
6) Display rows using .iloc.
7) Display rows in reverse order.

In [60]:
df.iloc[0]

Emp_ID      101
Name      Rahul
Salary    50000
Name: 0, dtype: object

In [61]:
df.iloc[-1]

Emp_ID       106
Name      Ananya
Salary     48000
Name: 5, dtype: object

In [62]:
df.iloc[:3]

   Emp_ID   Name  Salary
0     101  Rahul   50000
1     102  Priya   60000
2     103  Arjun   70000

In [63]:
df.iloc[::2]

   Emp_ID    Name  Salary
0     101   Rahul   50000
2     103   Arjun   70000
4     105  Vikram   62000

In [64]:
df.loc[0:2]

   Emp_ID   Name  Salary
0     101  Rahul   50000
1     102  Priya   60000
2     103  Arjun   70000

In [65]:
df.iloc[0:2]

   Emp_ID   Name  Salary
0     101  Rahul   50000
1     102  Priya   60000

In [66]:
df.iloc[::-1]

   Emp_ID    Name  Salary
5     106  Ananya   48000
4     105  Vikram   62000
3     104   Sneha   55000
2     103   Arjun   70000
1     102   Priya   60000
0     101   Rahul   50000

Update Rows
1) Update the salary of Employee ID 102.
2) Update multiple columns of Employee ID 102.
3) Increase the salary of all employees by 10%.
4) Update rows based on a condition.

In [68]:
df.loc[df["Emp_ID"] == 102, "Salary"] = 65000
df

   Emp_ID    Name  Salary
0     101   Rahul   50000
1     102   Priya   65000
2     103   Arjun   70000
3     104   Sneha   55000
4     105  Vikram   62000
5     106  Ananya   48000

In [69]:
df.loc[df["Emp_ID"] == 102, ["Name", "Salary"]] = ["Priya Sharma", 68000]
df

   Emp_ID          Name  Salary
0     101         Rahul   50000
1     102  Priya Sharma   68000
2     103         Arjun   70000
3     104         Sneha   55000
4     105        Vikram   62000
5     106        Ananya   48000

In [70]:
df["Salary"] = df["Salary"] * 1.10
df

   Emp_ID          Name   Salary
0     101         Rahul  55000.0
1     102  Priya Sharma  74800.0
2     103         Arjun  77000.0
3     104         Sneha  60500.0
4     105        Vikram  68200.0
5     106        Ananya  52800.0

In [71]:
df.loc[df["Salary"] < 60000, "Salary"] += 5000

df

   Emp_ID          Name   Salary
0     101         Rahul  60000.0
1     102  Priya Sharma  74800.0
2     103         Arjun  77000.0
3     104         Sneha  60500.0
4     105        Vikram  68200.0
5     106        Ananya  57800.0

Delete Rows
1) Delete Employee ID 103.
2) Delete multiple employee records.
3) Delete rows based on a salary condition.
4) Compare the DataFrame shape before and after deletion.

In [72]:
df.shape

(6, 3)

In [74]:
df = df[df["Emp_ID"] != 103]
df

   Emp_ID          Name   Salary
0     101         Rahul  60000.0
1     102  Priya Sharma  74800.0
3     104         Sneha  60500.0
4     105        Vikram  68200.0
5     106        Ananya  57800.0

In [75]:
df = df[~df["Emp_ID"].isin([105, 106])]
df

   Emp_ID          Name   Salary
0     101         Rahul  60000.0
1     102  Priya Sharma  74800.0
3     104         Sneha  60500.0

In [76]:
df = df[df["Salary"] <= 70000]
df

   Emp_ID   Name   Salary
0     101  Rahul  60000.0
3     104  Sneha  60500.0

In [77]:
df.shape

(2, 3)

In [78]:
df

   Emp_ID   Name   Salary
0     101  Rahul  60000.0
3     104  Sneha  60500.0

##Section D: Column-Level CRUD

Create Columns
1) Add a Department column.
2) Add an Experience column.
3) Add multiple new columns together.
4) Compare the DataFrame shape before and after adding columns.

In [79]:
df.shape

(2, 3)

In [80]:
df["Department"] = ["Tech", "HR"]
df

/tmp/ipykernel_660/4010028879.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Department"] = ["Tech", "HR"]

   Emp_ID   Name   Salary Department
0     101  Rahul  60000.0       Tech
3     104  Sneha  60500.0         HR

In [81]:
df["Experience"] = [3, 5]
df

/tmp/ipykernel_660/3488448552.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Experience"] = [3, 5]

   Emp_ID   Name   Salary Department  Experience
0     101  Rahul  60000.0       Tech           3
3     104  Sneha  60500.0         HR           5

In [82]:
df[["City", "Bonus"]] = [["Hyderabad", 5000], ["Bangalore", 6000]]
df

/tmp/ipykernel_660/2808205742.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[["City", "Bonus"]] = [["Hyderabad", 5000], ["Bangalore", 6000]]
/tmp/ipykernel_660/2808205742.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[["City", "Bonus"]] = [["Hyderabad", 5000], ["Bangalore", 6000]]

   Emp_ID   Name   Salary Department  Experience       City Bonus
0     101  Rahul  60000.0       Tech           3  Hyderabad  5000
3     104  Sneha  60500.0         HR           5  Bangalore  6000

In [83]:
df.shape

(2, 7)

In [84]:
df

   Emp_ID   Name   Salary Department  Experience       City Bonus
0     101  Rahul  60000.0       Tech           3  Hyderabad  5000
3     104  Sneha  60500.0         HR           5  Bangalore  6000

Read Columns
1) Display a single column.
2) Display multiple columns.
3) Display all numerical columns.
4) Display all categorical columns.
5) Display the first and last columns.

In [85]:
df["Name"]

0    Rahul
3    Sneha
Name: Name, dtype: object

In [86]:
df[["Name", "Salary"]]

    Name   Salary
0  Rahul  60000.0
3  Sneha  60500.0

In [87]:
df.select_dtypes(include=[np.number])

   Emp_ID   Salary  Experience
0     101  60000.0           3
3     104  60500.0           5

In [88]:
df.select_dtypes(include=["object"])

    Name Department       City Bonus
0  Rahul       Tech  Hyderabad  5000
3  Sneha         HR  Bangalore  6000

In [89]:
df.iloc[:, [0, -1]]

   Emp_ID Bonus
0     101  5000
3     104  6000

Update Columns
1) Update one value in the Salary column.
2) Increase the entire Salary column by 10%.
3) Update Department values.
4) Replace column values using a condition.

In [91]:
df.loc[df.index[0], "Salary"] = 62000.0
df

   Emp_ID   Name   Salary Department  Experience       City Bonus
0     101  Rahul  62000.0       Tech           3  Hyderabad  5000
3     104  Sneha  60500.0         HR           5  Bangalore  6000

In [93]:
df["Salary"] = df["Salary"] * 1.10
df

/tmp/ipykernel_660/824741619.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Salary"] = df["Salary"] * 1.10

   Emp_ID   Name   Salary Department  Experience       City Bonus
0     101  Rahul  75020.0       Tech           3  Hyderabad  5000
3     104  Sneha  73205.0         HR           5  Bangalore  6000

In [94]:
df["Department"] = df["Department"].str.upper()
df

/tmp/ipykernel_660/77466032.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Department"] = df["Department"].str.upper()

   Emp_ID   Name   Salary Department  Experience       City Bonus
0     101  Rahul  75020.0       TECH           3  Hyderabad  5000
3     104  Sneha  73205.0         HR           5  Bangalore  6000

In [95]:
df["Department"] = df["Department"].replace({"TECH": "IT"})
df

/tmp/ipykernel_660/2197154756.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Department"] = df["Department"].replace({"TECH": "IT"})

   Emp_ID   Name   Salary Department  Experience       City Bonus
0     101  Rahul  75020.0         IT           3  Hyderabad  5000
3     104  Sneha  73205.0         HR           5  Bangalore  6000

In [96]:
df[["Name", "Salary", "Department"]]

    Name   Salary Department
0  Rahul  75020.0         IT
3  Sneha  73205.0         HR

Delete Columns
1) Delete one column.
2) Delete multiple columns.
3) Compare the DataFrame shape before and after deletion.

In [97]:
df.shape

(2, 7)

In [98]:
df = df.drop(columns=["Bonus"])
df

   Emp_ID   Name   Salary Department  Experience       City
0     101  Rahul  75020.0         IT           3  Hyderabad
3     104  Sneha  73205.0         HR           5  Bangalore

In [99]:
df = df.drop(columns=["City", "Experience"])
df

   Emp_ID   Name   Salary Department
0     101  Rahul  75020.0         IT
3     104  Sneha  73205.0         HR

In [100]:
df.shape

(2, 4)

In [101]:
df

   Emp_ID   Name   Salary Department
0     101  Rahul  75020.0         IT
3     104  Sneha  73205.0         HR

##Section E: Cell-Level CRUD

1) Read a cell using row and column labels (.loc).
2) Read a cell using row and column positions (.iloc).
3) Update a single cell value.
4) Update multiple cell values.
5) Replace selected cells with missing (NaN) values.

In [104]:
df.loc[df.index[0], "Name"]

'Rahul'

In [105]:
df.iloc[0, 1]

'Rahul'

In [107]:
df.loc[df.index[0], "Salary"] = 72000.0
df

   Emp_ID   Name   Salary Department
0     101  Rahul  72000.0         IT
3     104  Sneha  73205.0         HR

In [108]:
df.loc[df.index[0:2], "Department"] = ["Software Development", "Human Resources"]
df

   Emp_ID   Name   Salary            Department
0     101  Rahul  72000.0  Software Development
3     104  Sneha  73205.0       Human Resources

In [109]:
df.loc[df.index[1], "Salary"] = np.nan
df.loc[df.index[0], "Department"] = np.nan

df

   Emp_ID   Name   Salary       Department
0     101  Rahul  72000.0              NaN
3     104  Sneha      NaN  Human Resources