#PANDAS – Assignment 2

##Topic 7: Row & Column Selection

Q26. Select rows using .loc().

In [1]:
import pandas as pd

In [3]:
df_q26 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Marks": [85, 92, 78, 88, 95],
    "Subject": ["Math", "Science", "History", "Math", "Science"]
}, index=["R1", "R2", "R3", "R4", "R5"])

df_q26

       Name  Marks  Subject
R1    Alice     85     Math
R2      Bob     92  Science
R3  Charlie     78  History
R4    David     88     Math
R5      Eva     95  Science

In [5]:
# Single row selection
row_single = df_q26.loc["R1"]
row_single

Name       Alice
Marks         85
Subject     Math
Name: R1, dtype: object

In [8]:
# Multiple rows using label slice (inclusive of stop label)
row_slice = df_q26.loc["R2":"R4"]
row_slice

       Name  Marks  Subject
R2      Bob     92  Science
R3  Charlie     78  History
R4    David     88     Math

In [9]:
# Conditional row selection using boolean mask
row_condition = df_q26.loc[df_q26["Marks"] > 85]
row_condition

     Name  Marks  Subject
R2    Bob     92  Science
R4  David     88     Math
R5    Eva     95  Science

Q27. Select rows using .iloc().

In [10]:
df_q27 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Marks": [85, 92, 78, 88, 95],
    "Subject": ["Math", "Science", "History", "Math", "Science"]
})
df_q27

      Name  Marks  Subject
0    Alice     85     Math
1      Bob     92  Science
2  Charlie     78  History
3    David     88     Math
4      Eva     95  Science

In [11]:
# Single row by integer position
row_pos = df_q27.iloc[0]
row_pos

Name       Alice
Marks         85
Subject     Math
Name: 0, dtype: object

In [13]:
# Range of rows by integer slice (exclusive of stop index)
rows_range = df_q27.iloc[1:4]
rows_range

      Name  Marks  Subject
1      Bob     92  Science
2  Charlie     78  History
3    David     88     Math

In [14]:
# Arbitrary rows using a list of positions
rows_list = df_q27.iloc[[0, 2, 4]]
rows_list

      Name  Marks  Subject
0    Alice     85     Math
2  Charlie     78  History
4      Eva     95  Science

Q28. Demonstrate the difference between .loc() and .iloc() using the same DataFrame.

In [15]:
df_q28 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Marks": [85, 92, 78, 88]
}, index=[10, 20, 30, 40])
df_q28

       Name  Marks
10    Alice     85
20      Bob     92
30  Charlie     78
40    David     88

In [17]:
# .loc searches for the literal label 30 and INCLUDES it
loc_demo = df_q28.loc[10:30]
loc_demo

       Name  Marks
10    Alice     85
20      Bob     92
30  Charlie     78

In [18]:
# .iloc counts 0-based integer positions and EXCLUDES stop index 3
iloc_demo = df_q28.iloc[0:3]
iloc_demo

       Name  Marks
10    Alice     85
20      Bob     92
30  Charlie     78

Q29. Select a single column, multiple columns, and a range of columns.

In [19]:
df_q29 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [21, 22, 20, 23],
    "City": ["Hyderabad", "Bangalore", "Chennai", "Mumbai"],
    "Marks": [85, 92, 78, 88]
})
df_q29

      Name  Age       City  Marks
0    Alice   21  Hyderabad     85
1      Bob   22  Bangalore     92
2  Charlie   20    Chennai     78
3    David   23     Mumbai     88

In [20]:
# Single column
col_single = df_q29["Name"]
col_single

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

In [22]:
# Multiple columns using list
col_multi = df_q29[["Name", "Marks"]]
col_multi

      Name  Marks
0    Alice     85
1      Bob     92
2  Charlie     78
3    David     88

In [23]:
# Range of columns using .loc slice
col_range = df_q29.loc[:, "Age":"Marks"]
col_range

   Age       City  Marks
0   21  Hyderabad     85
1   22  Bangalore     92
2   20    Chennai     78
3   23     Mumbai     88

##Topic 8: Copying Data

Q30. Create a deep copy of a DataFrame using .copy() and verify that modifying the copy does not affect the original DataFrame.

In [24]:
df_original = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Marks": [85, 92, 78]
})
df_original

      Name  Marks
0    Alice     85
1      Bob     92
2  Charlie     78

In [25]:
# Create deep copy
df_copy = df_original.copy(deep=True)
df_copy

      Name  Marks
0    Alice     85
1      Bob     92
2  Charlie     78

In [26]:
# Modify the copy using standard .loc to prevent ChainedAssignment warnings
df_copy.loc[0, "Marks"] = 100
df_copy

      Name  Marks
0    Alice    100
1      Bob     92
2  Charlie     78

##Topic 9: Ranking & Sorting

Q31. Rank students based on Marks using .rank().

In [27]:
df_q31 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Marks": [85, 92, 78, 88, 92]
})
df_q31

      Name  Marks
0    Alice     85
1      Bob     92
2  Charlie     78
3    David     88
4      Eva     92

In [28]:
# Highest marks get rank 1
df_q31["Rank"] = df_q31["Marks"].rank(ascending=False, method="min")
display(df_q31)

      Name  Marks  Rank
0    Alice     85   4.0
1      Bob     92   1.0
2  Charlie     78   5.0
3    David     88   3.0
4      Eva     92   1.0

Q32. Sort the DataFrame by one column using .sort_values().

In [29]:
df_q32 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Marks": [85, 92, 78, 88]
})
df_q32

      Name  Marks
0    Alice     85
1      Bob     92
2  Charlie     78
3    David     88

In [30]:
sorted_df = df_q32.sort_values(by="Marks", ascending=True)
display(sorted_df)

      Name  Marks
2  Charlie     78
0    Alice     85
3    David     88
1      Bob     92

Q33. Sort the DataFrame using multiple columns.

In [31]:
df_q33 = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "HR", "Finance"],
    "Salary": [75000, 50000, 85000, 60000, 90000]
})
df_q33

  Department  Salary
0         IT   75000
1         HR   50000
2         IT   85000
3         HR   60000
4    Finance   90000

In [32]:
# Sort Department alphabetically ascending, then Salary descending
multi_sorted = df_q33.sort_values(by=["Department", "Salary"], ascending=[True, False])
display(multi_sorted)

  Department  Salary
4    Finance   90000
3         HR   60000
1         HR   50000
2         IT   85000
0         IT   75000

Q34. Sort the DataFrame by row index using .sort_index().

In [33]:
df_q34 = pd.DataFrame({
    "Score": [78, 92, 85]
}, index=[302, 101, 205])
df_q34

     Score
302     78
101     92
205     85

In [34]:
# Sort index ascending
sorted_index_df = df_q34.sort_index(ascending=True)
display(sorted_index_df)

     Score
101     92
205     85
302     78

##Topic 10: Iterating Through Data

Q35. Iterate through all rows using .iterrows().

In [35]:
df_q35 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Marks": [85, 92, 78]
})
df_q35

      Name  Marks
0    Alice     85
1      Bob     92
2  Charlie     78

In [36]:
for idx, row in df_q35.iterrows():
    print(f"Index: {idx} | Student: {row['Name']} | Score: {row['Marks']}")

Index: 0 | Student: Alice | Score: 85
Index: 1 | Student: Bob | Score: 92
Index: 2 | Student: Charlie | Score: 78

Q36. Iterate through all columns using .items() (or .iteritems() if applicable).

In [37]:
df_q36 = pd.DataFrame({
    "Name": ["Alice", "Bob"],
    "Age": [21, 22],
    "Score": [85, 92]
})
df_q36

    Name  Age  Score
0  Alice   21     85
1    Bob   22     92

In [38]:
for col_name, col_series in df_q36.items():
    print(f"Column: {col_name} (dtype: {col_series.dtype})")
    print(col_series.tolist())
    print("-" * 30)

Column: Name (dtype: object)
['Alice', 'Bob']
------------------------------
Column: Age (dtype: int64)
[21, 22]
------------------------------
Column: Score (dtype: int64)
[85, 92]
------------------------------

##Topic 11: Mathematical Operations

Q37. Perform arithmetic operations (+, -, *, /) on all numeric columns of the DataFrame.

In [39]:
df_q37 = pd.DataFrame({
    "Item": ["Pen", "Notebook", "Binder"],
    "Price": [10, 50, 80],
    "Stock": [100, 200, 150]
})
df_q37

       Item  Price  Stock
0       Pen     10    100
1  Notebook     50    200
2    Binder     80    150

In [41]:
import numpy as np

In [43]:
numeric_part = df_q37.select_dtypes(include=[np.number])
numeric_part

   Price  Stock
0     10    100
1     50    200
2     80    150

In [44]:
# Addition (+ 5)
display(numeric_part + 5)

   Price  Stock
0     15    105
1     55    205
2     85    155

In [45]:
# Subtraction (- 2)
display(numeric_part - 2)

   Price  Stock
0      8     98
1     48    198
2     78    148

In [46]:
# Multiplication (* 2)
display(numeric_part * 2)

   Price  Stock
0     20    200
1    100    400
2    160    300

In [47]:
# Division (/ 2)
display(numeric_part / 2)

   Price  Stock
0    5.0   50.0
1   25.0  100.0
2   40.0   75.0

Q38. Create a new column named Bonus by increasing the Marks column by 10%.

In [48]:
df_q38 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Marks": [85, 92, 78]
})
df_q38

      Name  Marks
0    Alice     85
1      Bob     92
2  Charlie     78

In [49]:
df_q38["Bonus"] = df_q38["Marks"] * 1.10
display(df_q38)

      Name  Marks  Bonus
0    Alice     85   93.5
1      Bob     92  101.2
2  Charlie     78   85.8

##Topic 12: Column Information

Q39. Display all column names using .columns.

In [50]:
df_q39 = pd.DataFrame({
    "Name": ["Alice"], "Age": [21], "Gender": ["Female"], "City": ["Hyderabad"], "Marks": [85]
})
df_q39

    Name  Age  Gender       City  Marks
0  Alice   21  Female  Hyderabad     85

In [51]:
df_q39.columns

Index(['Name', 'Age', 'Gender', 'City', 'Marks'], dtype='object')

Q40. Find the index position of the Marks column.

In [52]:
df_q40 = pd.DataFrame({
    "Name": ["Alice"], "Age": [21], "Gender": ["Female"], "Marks": [85], "City": ["Hyderabad"]
})
df_q40

    Name  Age  Gender  Marks       City
0  Alice   21  Female     85  Hyderabad

In [53]:
position = df_q40.columns.get_loc("Marks")
position

3

Q41. Convert the column names into a Python list using .tolist().

In [54]:
df_q41 = pd.DataFrame({
    "Name": ["Alice"], "Age": [21], "Marks": [85]
})
df_q41

    Name  Age  Marks
0  Alice   21     85

In [55]:
cols_list = df_q41.columns.tolist()
cols_list

['Name', 'Age', 'Marks']

In [56]:
type(cols_list)

list

Q42. Convert the DataFrame into a NumPy array using .values.

In [57]:
df_q42 = pd.DataFrame({
    "Product": ["Laptop", "Mouse", "Keyboard"],
    "Price": [1200, 25, 75]
})
df_q42

    Product  Price
0    Laptop   1200
1     Mouse     25
2  Keyboard     75

In [58]:
array_data = df_q42.values
array_data

array([['Laptop', 1200],
       ['Mouse', 25],
       ['Keyboard', 75]], dtype=object)

In [59]:
type(array_data)

numpy.ndarray

##Topic 13: Renaming & Selecting Columns

Q43. Rename one column and then rename multiple columns using .rename().

In [60]:
df_q43 = pd.DataFrame({
    "Name": ["Alice"], "Age": [21], "City": ["Hyderabad"], "Marks": [85]
})
df_q43

    Name  Age       City  Marks
0  Alice   21  Hyderabad     85

In [61]:
# Rename single column
df_q43 = df_q43.rename(columns={"Marks": "Score"})
display(df_q43)

    Name  Age       City  Score
0  Alice   21  Hyderabad     85

In [62]:
# Rename multiple columns
df_q43 = df_q43.rename(columns={"Name": "Student_Name", "Age": "Student_Age"})
display(df_q43)

  Student_Name  Student_Age       City  Score
0        Alice           21  Hyderabad     85

Q44. Select columns using column names.

In [63]:
df_q44 = pd.DataFrame({
    "Name": ["Alice", "Bob"],
    "Age": [21, 22],
    "City": ["Hyderabad", "Bangalore"],
    "Marks": [85, 92]
})
df_q44

    Name  Age       City  Marks
0  Alice   21  Hyderabad     85
1    Bob   22  Bangalore     92

In [64]:
selected_cols = df_q44[["Name", "City"]]
display(selected_cols)

    Name       City
0  Alice  Hyderabad
1    Bob  Bangalore

Q45. Select columns using column index positions.

In [65]:
df_q45 = pd.DataFrame({
    "Name": ["Alice", "Bob"],
    "Age": [21, 22],
    "City": ["Hyderabad", "Bangalore"],
    "Marks": [85, 92]
})
df_q45

    Name  Age       City  Marks
0  Alice   21  Hyderabad     85
1    Bob   22  Bangalore     92

In [66]:
# Select columns at index 0 ('Name') and index 3 ('Marks')
selected_by_pos = df_q45.iloc[:, [0, 3]]
display(selected_by_pos)

    Name  Marks
0  Alice     85
1    Bob     92

Q46. Select only numeric columns.

In [67]:
df_q46 = pd.DataFrame({
    "Name": ["Alice", "Bob"],
    "Age": [21, 22],
    "Score": [85.5, 92.0],
    "Enrolled": [True, False]
})
df_q46

    Name  Age  Score  Enrolled
0  Alice   21   85.5      True
1    Bob   22   92.0     False

In [68]:
numeric_cols = df_q46.select_dtypes(include=[np.number])
display(numeric_cols)

   Age  Score
0   21   85.5
1   22   92.0

Q47. Select only object (string) columns.

In [69]:
df_q47 = pd.DataFrame({
    "Name": ["Alice", "Bob"],
    "City": ["Hyderabad", "Bangalore"],
    "Age": [21, 22],
    "Score": [85, 92]
})
df_q47

    Name       City  Age  Score
0  Alice  Hyderabad   21     85
1    Bob  Bangalore   22     92

In [70]:
object_cols = df_q47.select_dtypes(include=["object"])
display(object_cols)

    Name       City
0  Alice  Hyderabad
1    Bob  Bangalore

##Topic 14: Practice Exercise

Q48. Create an employee DataFrame and perform head(), tail(), info(), describe(), shape, and sample().

In [72]:
emp_data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": ["Prashanth", "Venu", "Vamshi", "Sravan", "Chinna", "Chanti", "Bekkam", "Diamond", "Star", "Rebba"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "Finance", "HR", "Sales", "IT", "Operations"],
    "Salary": [75000, 60000, 85000, 72000, 58000, 90000, 64000, 52000, 78000, 82000],
    "Experience": [3, 2, 5, 3, 1, 6, 2, 1, 4, 5]
}
emp_df = pd.DataFrame(emp_data)
emp_df

   Emp_ID       Name  Department  Salary  Experience
0     101  Prashanth          IT   75000           3
1     102       Venu          HR   60000           2
2     103     Vamshi     Finance   85000           5
3     104     Sravan          IT   72000           3
4     105     Chinna       Sales   58000           1
5     106     Chanti     Finance   90000           6
6     107     Bekkam          HR   64000           2
7     108    Diamond       Sales   52000           1
8     109       Star          IT   78000           4
9     110      Rebba  Operations   82000           5

In [73]:
display(emp_df.head(3))

   Emp_ID       Name Department  Salary  Experience
0     101  Prashanth         IT   75000           3
1     102       Venu         HR   60000           2
2     103     Vamshi    Finance   85000           5

In [74]:
display(emp_df.tail(3))

   Emp_ID     Name  Department  Salary  Experience
7     108  Diamond       Sales   52000           1
8     109     Star          IT   78000           4
9     110    Rebba  Operations   82000           5

In [75]:
emp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Emp_ID      10 non-null     int64
 1   Name        10 non-null     object
 2   Department  10 non-null     object
 3   Salary      10 non-null     int64
 4   Experience  10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [76]:
display(emp_df.describe(include="all"))

           Emp_ID       Name Department       Salary  Experience
count    10.00000         10         10     10.00000    10.00000
unique        NaN         10          5          NaN         NaN
top           NaN  Prashanth         IT          NaN         NaN
freq          NaN          1          3          NaN         NaN
mean    105.50000        NaN        NaN  71600.00000     3.20000
std       3.02765        NaN        NaN  12650.86734     1.75119
min     101.00000        NaN        NaN  52000.00000     1.00000
25%     103.25000        NaN        NaN  61000.00000     2.00000
50%     105.50000        NaN        NaN  73500.00000     3.00000
75%     107.75000        NaN        NaN  81000.00000     4.75000
max     110.00000        NaN        NaN  90000.00000     6.00000

In [77]:
display(emp_df.sample(3))

   Emp_ID       Name  Department  Salary  Experience
9     110      Rebba  Operations   82000           5
0     101  Prashanth          IT   75000           3
8     109       Star          IT   78000           4

Q49. On the same employee DataFrame, perform .loc(), .iloc(), .sort_values(), .rank(), and .copy().

In [100]:
emp_df_49 = pd.DataFrame({
    "Emp_ID": [101, 102, 103, 104],
    "Name": ["bonu", "sony", "palli", "lavi"],
    "Salary": [75000, 60000, 85000, 72000]
}, index=["E1", "E2", "E3", "E4"])
emp_df_49

    Emp_ID   Name  Salary
E1     101   bonu   75000
E2     102   sony   60000
E3     103  palli   85000
E4     104   lavi   72000

In [101]:
# 1. .loc() and .iloc()
display(emp_df_49.loc[["E2"]])

    Emp_ID  Name  Salary
E2     102  sony   60000

In [102]:
display(emp_df_49.iloc[0:2])

    Emp_ID  Name  Salary
E1     101  bonu   75000
E2     102  sony   60000

In [103]:
# 2. .sort_values()
display(emp_df_49.sort_values(by="Salary", ascending=False))

    Emp_ID   Name  Salary
E3     103  palli   85000
E1     101   bonu   75000
E4     104   lavi   72000
E2     102   sony   60000

In [104]:
# 3. .rank()
emp_df_49["Salary_Rank"] = emp_df_49["Salary"].rank(ascending=False)
display(emp_df_49)

    Emp_ID   Name  Salary  Salary_Rank
E1     101   bonu   75000          2.0
E2     102   sony   60000          4.0
E3     103  palli   85000          1.0
E4     104   lavi   72000          3.0

In [105]:
# 4. .copy()
emp_copy = emp_df_49.copy(deep=True)
emp_copy

    Emp_ID   Name  Salary  Salary_Rank
E1     101   bonu   75000          2.0
E2     102   sony   60000          4.0
E3     103  palli   85000          1.0
E4     104   lavi   72000          3.0

In [106]:
emp_copy.loc["E1", "Salary"] = 99999

In [107]:
emp_df_49.loc["E1", "Salary"]

np.int64(75000)

In [108]:
emp_copy.loc["E1", "Salary"]

np.int64(99999)

Q50. Create a complete student management DataFrame from scratch, save it as CSV and Excel, reload both files, inspect the data, rename columns, sort the data, select rows using .loc() and .iloc(), and display the final DataFrame.

In [88]:
student_mgmt = pd.DataFrame({
    "StudentID": [1, 2, 3, 4, 5],
    "StudentName": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Course": ["Math", "Physics", "Chemistry", "Math", "Biology"],
    "Marks": [85, 92, 78, 88, 95]
})
student_mgmt

   StudentID StudentName     Course  Marks
0          1       Alice       Math     85
1          2         Bob    Physics     92
2          3     Charlie  Chemistry     78
3          4       David       Math     88
4          5         Eva    Biology     95

Save as CSV and Excel

In [89]:
student_mgmt.to_csv("student_records.csv", index=False)

In [90]:
student_mgmt.to_excel("student_records.xlsx", index=False)

Reload both files

In [92]:
reloaded_csv = pd.read_csv("student_records.csv")
reloaded_csv

   StudentID StudentName     Course  Marks
0          1       Alice       Math     85
1          2         Bob    Physics     92
2          3     Charlie  Chemistry     78
3          4       David       Math     88
4          5         Eva    Biology     95

In [93]:
reloaded_excel = pd.read_excel("student_records.xlsx")
reloaded_excel

   StudentID StudentName     Course  Marks
0          1       Alice       Math     85
1          2         Bob    Physics     92
2          3     Charlie  Chemistry     78
3          4       David       Math     88
4          5         Eva    Biology     95

In [94]:
reloaded_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   StudentID    5 non-null      int64
 1   StudentName  5 non-null      object
 2   Course       5 non-null      object
 3   Marks        5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

Rename columns

In [95]:
processed_df = reloaded_excel.rename(columns={"StudentName": "FullName", "Marks": "FinalScore"})
processed_df

   StudentID FullName     Course  FinalScore
0          1    Alice       Math          85
1          2      Bob    Physics          92
2          3  Charlie  Chemistry          78
3          4    David       Math          88
4          5      Eva    Biology          95

Sort data by FinalScore descending and reset index

In [96]:
processed_df = processed_df.sort_values(by="FinalScore", ascending=False).reset_index(drop=True)
processed_df

   StudentID FullName     Course  FinalScore
0          5      Eva    Biology          95
1          2      Bob    Physics          92
2          4    David       Math          88
3          1    Alice       Math          85
4          3  Charlie  Chemistry          78

In [97]:
# Select rows using .loc and .iloc
display(processed_df.loc[[0]])

   StudentID FullName   Course  FinalScore
0          5      Eva  Biology          95

In [98]:
# Row Selection with .iloc[1:3] (Rankers 2 and 3)
display(processed_df.iloc[1:3])

   StudentID FullName   Course  FinalScore
1          2      Bob  Physics          92
2          4    David     Math          88

In [99]:
display(processed_df)

   StudentID FullName     Course  FinalScore
0          5      Eva    Biology          95
1          2      Bob    Physics          92
2          4    David       Math          88
3          1    Alice       Math          85
4          3  Charlie  Chemistry          78