#📌 Pandas Advanced Data Analysis Workbook

🔹 Dataset for All Tasks
Use the following Employee Dataset:

```
df = pd.DataFrame({ "Emp_ID":[101,102,103,104,105,106,107,108],
"Name":["Rahul","Priya","Arjun","Sneha","Kiran","Pooja","Vikram","Anjali"], "Department":["DS","HR","IT","Finance","IT","HR","DS","Finance"], "City":["Hyderabad","Bangalore","Chennai","Mumbai","Hyderabad","Bangalore","Chennai","Mumbai"], "Salary":[50000,45000,60000,55000,70000,48000,75000,65000], "Experience":[2,4,5,3,8,4,9,6], "Rating":[4,3,5,4,5,3,5,4] })

```

In [72]:
import pandas as pd
import numpy as np

# Base dataset
df = pd.DataFrame({
    "Emp_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ["Rahul", "Priya", "Arjun", "Sneha", "Kiran", "Pooja", "Vikram", "Anjali"],
    "Department": ["DS", "HR", "IT", "Finance", "IT", "HR", "DS", "Finance"],
    "City": ["Hyderabad", "Bangalore", "Chennai", "Mumbai", "Hyderabad", "Bangalore", "Chennai", "Mumbai"],
    "Salary": [50000, 45000, 60000, 55000, 70000, 48000, 75000, 65000],
    "Experience": [2, 4, 5, 3, 8, 4, 9, 6],
    "Rating": [4, 3, 5, 4, 5, 3, 5, 4]
})

display(df)

   Emp_ID    Name Department       City  Salary  Experience  Rating
0     101   Rahul         DS  Hyderabad   50000           2       4
1     102   Priya         HR  Bangalore   45000           4       3
2     103   Arjun         IT    Chennai   60000           5       5
3     104   Sneha    Finance     Mumbai   55000           3       4
4     105   Kiran         IT  Hyderabad   70000           8       5
5     106   Pooja         HR  Bangalore   48000           4       3
6     107  Vikram         DS    Chennai   75000           9       5
7     108  Anjali    Finance     Mumbai   65000           6       4

##🔹 Section A: Filtering

###1. Basic Filtering

1. Display employees whose salary is greater than 50000.

In [73]:
display(df[df["Salary"] > 50000])

   Emp_ID    Name Department       City  Salary  Experience  Rating
2     103   Arjun         IT    Chennai   60000           5       5
3     104   Sneha    Finance     Mumbai   55000           3       4
4     105   Kiran         IT  Hyderabad   70000           8       5
6     107  Vikram         DS    Chennai   75000           9       5
7     108  Anjali    Finance     Mumbai   65000           6       4

2. Display employees whose experience is greater than 5 years.

In [74]:
display(df[df["Experience"] > 5])

   Emp_ID    Name Department       City  Salary  Experience  Rating
4     105   Kiran         IT  Hyderabad   70000           8       5
6     107  Vikram         DS    Chennai   75000           9       5
7     108  Anjali    Finance     Mumbai   65000           6       4

3. Display employees whose rating is 5.

In [75]:
display(df[df["Rating"] == 5])

   Emp_ID    Name Department       City  Salary  Experience  Rating
2     103   Arjun         IT    Chennai   60000           5       5
4     105   Kiran         IT  Hyderabad   70000           8       5
6     107  Vikram         DS    Chennai   75000           9       5

4. Display employees from Hyderabad.

In [76]:
display(df[df["City"] == "Hyderabad"])

   Emp_ID   Name Department       City  Salary  Experience  Rating
0     101  Rahul         DS  Hyderabad   50000           2       4
4     105  Kiran         IT  Hyderabad   70000           8       5

5. Display employees belonging to the IT department.

In [77]:
display(df[df["Department"] == "IT"])

   Emp_ID   Name Department       City  Salary  Experience  Rating
2     103  Arjun         IT    Chennai   60000           5       5
4     105  Kiran         IT  Hyderabad   70000           8       5

###2. Multiple Condition Filtering

1. Display employees from the IT department whose salary is greater than 60000.

In [78]:
display(df[(df["Department"] == "IT") & (df["Salary"] > 60000)])

   Emp_ID   Name Department       City  Salary  Experience  Rating
4     105  Kiran         IT  Hyderabad   70000           8       5

2. Display employees from the DS department whose rating is 5.

In [79]:
display(df[(df["Department"] == "DS") & (df["Rating"] == 5)])

   Emp_ID    Name Department     City  Salary  Experience  Rating
6     107  Vikram         DS  Chennai   75000           9       5

3. Display employees whose salary is greater than 50000 and rating is greater than 4.

In [80]:
display(df[(df["Salary"] > 50000) & (df["Rating"] > 4)])

   Emp_ID    Name Department       City  Salary  Experience  Rating
2     103   Arjun         IT    Chennai   60000           5       5
4     105   Kiran         IT  Hyderabad   70000           8       5
6     107  Vikram         DS    Chennai   75000           9       5

4. Display employees from Hyderabad or Chennai.

In [81]:
display(df[(df["City"] == "Hyderabad") | (df["City"] == "Chennai")])

   Emp_ID    Name Department       City  Salary  Experience  Rating
0     101   Rahul         DS  Hyderabad   50000           2       4
2     103   Arjun         IT    Chennai   60000           5       5
4     105   Kiran         IT  Hyderabad   70000           8       5
6     107  Vikram         DS    Chennai   75000           9       5

In [82]:
display(df[df["City"].isin(["Hyderabad", "Chennai"])])

   Emp_ID    Name Department       City  Salary  Experience  Rating
0     101   Rahul         DS  Hyderabad   50000           2       4
2     103   Arjun         IT    Chennai   60000           5       5
4     105   Kiran         IT  Hyderabad   70000           8       5
6     107  Vikram         DS    Chennai   75000           9       5

##🔹 Section B: GroupBy

###3. GroupBy Basics

1. Group employees by Department.

In [83]:
dept_group = df.groupby("Department")
dept_group.first()

            Emp_ID   Name       City  Salary  Experience  Rating
Department
DS             101  Rahul  Hyderabad   50000           2       4
Finance        104  Sneha     Mumbai   55000           3       4
HR             102  Priya  Bangalore   45000           4       3
IT             103  Arjun    Chennai   60000           5       5

2. Display all department groups.

In [84]:
for dept, group in dept_group:
    display(group)

   Emp_ID    Name Department       City  Salary  Experience  Rating
0     101   Rahul         DS  Hyderabad   50000           2       4
6     107  Vikram         DS    Chennai   75000           9       5

   Emp_ID    Name Department    City  Salary  Experience  Rating
3     104   Sneha    Finance  Mumbai   55000           3       4
7     108  Anjali    Finance  Mumbai   65000           6       4

   Emp_ID   Name Department       City  Salary  Experience  Rating
1     102  Priya         HR  Bangalore   45000           4       3
5     106  Pooja         HR  Bangalore   48000           4       3

   Emp_ID   Name Department       City  Salary  Experience  Rating
2     103  Arjun         IT    Chennai   60000           5       5
4     105  Kiran         IT  Hyderabad   70000           8       5

3. Count the total number of groups.

In [85]:
dept_group.ngroups

4

4. Display the size of each group.

In [86]:
dept_group.size()

Department
DS         2
Finance    2
HR         2
IT         2
dtype: int64

###4. GroupBy Analysis

1. Count employees department-wise.

In [87]:
display(df.groupby("Department")["Emp_ID"].count())

Department
DS         2
Finance    2
HR         2
IT         2
Name: Emp_ID, dtype: int64

2. Count employees city-wise.

In [88]:
display(df.groupby("City")["Emp_ID"].count())

City
Bangalore    2
Chennai      2
Hyderabad    2
Mumbai       2
Name: Emp_ID, dtype: int64

3. Calculate the total salary department-wise.

In [89]:
display(df.groupby("Department")["Salary"].sum())

Department
DS         125000
Finance    120000
HR          93000
IT         130000
Name: Salary, dtype: int64

4. Calculate the average salary department-wise.

In [90]:
display(df.groupby("Department")["Salary"].mean())

Department
DS         62500.0
Finance    60000.0
HR         46500.0
IT         65000.0
Name: Salary, dtype: float64

5. Calculate the minimum salary department-wise.

In [91]:
display(df.groupby("Department")["Salary"].min())

Department
DS         50000
Finance    55000
HR         45000
IT         60000
Name: Salary, dtype: int64

6. Calculate the maximum salary department-wise.

In [92]:
display(df.groupby("Department")["Salary"].max())

Department
DS         75000
Finance    65000
HR         48000
IT         70000
Name: Salary, dtype: int64

7. Calculate the average rating department-wise.

In [93]:
display(df.groupby("Department")["Rating"].mean())

Department
DS         4.5
Finance    4.0
HR         3.0
IT         5.0
Name: Rating, dtype: float64

## 🔹 Section C: Aggregation Functions

##5. Basic Aggregations

1. Find the total salary of all employees.

In [94]:
df["Salary"].sum()

np.int64(468000)

2. Find the average salary of all employees.

In [95]:
df["Salary"].mean()

np.float64(58500.0)

3. Find the minimum salary.

In [96]:
df["Salary"].min()

45000

4. Find the maximum salary.

In [97]:
df["Salary"].max()

75000

5. Find the average experience.

In [98]:
df["Experience"].mean()

np.float64(5.125)

6. Find the maximum rating.

In [99]:
df["Rating"].max()

5

###6. Department-wise Aggregations

1. Find the total salary department-wise.

In [100]:
display(df.groupby("Department")["Salary"].sum())

Department
DS         125000
Finance    120000
HR          93000
IT         130000
Name: Salary, dtype: int64

2. Find the average salary department-wise.

In [101]:
display(df.groupby("Department")["Salary"].mean())

Department
DS         62500.0
Finance    60000.0
HR         46500.0
IT         65000.0
Name: Salary, dtype: float64

3. Find the minimum salary department-wise.

In [102]:
display(df.groupby("Department")["Salary"].min())

Department
DS         50000
Finance    55000
HR         45000
IT         60000
Name: Salary, dtype: int64

4. Find the maximum salary department-wise.

In [103]:
display(df.groupby("Department")["Salary"].max())

Department
DS         75000
Finance    65000
HR         48000
IT         70000
Name: Salary, dtype: int64

5. Find the average experience department-wise.

In [104]:
display(df.groupby("Department")["Experience"].mean())

Department
DS         5.5
Finance    4.5
HR         4.0
IT         6.5
Name: Experience, dtype: float64

##🔹 Section D: .agg() Method

###7. Single Column Aggregation

1. Apply sum() on the Salary column using .agg().

In [105]:
df["Salary"].agg("sum")

np.int64(468000)

2. Apply mean() on the Salary column using .agg().

In [106]:
df["Salary"].agg("mean")

np.float64(58500.0)

3. Apply min() on the Salary column using .agg().

In [107]:
df["Salary"].agg("min")

45000

4. Apply max() on the Salary column using .agg().

In [108]:
df["Salary"].agg("max")

75000

5. Apply count() on the Salary column using .agg().

In [109]:
df["Salary"].agg("count")

np.int64(8)

###8. Multiple Aggregations

1. Apply sum() and mean() on the Salary column.

In [110]:
display(df["Salary"].agg(["sum", "mean"]))

sum     468000.0
mean     58500.0
Name: Salary, dtype: float64

2. Apply min() and max() on the Salary column.

In [111]:
display(df["Salary"].agg(["min", "max"]))

min    45000
max    75000
Name: Salary, dtype: int64

3. Apply count(), mean(), and max() on the Experience column.

In [112]:
display(df["Experience"].agg(["count", "mean", "max"]))

count    8.000
mean     5.125
max      9.000
Name: Experience, dtype: float64

4. Apply multiple aggregation functions (count(), sum(), mean(), min(), max()) on Salary department-wise.

In [113]:
display(df.groupby("Department")["Salary"].agg(["count", "sum", "mean", "min", "max"]))

            count     sum     mean    min    max
Department
DS              2  125000  62500.0  50000  75000
Finance         2  120000  60000.0  55000  65000
HR              2   93000  46500.0  45000  48000
IT              2  130000  65000.0  60000  70000

##🔹 Section E: Apply Function

###9. Apply Function Practice

In [114]:
def add_ten_percent(val):
    return val * 1.10

def calc_annual(val):
    return val * 12

def calc_bonus(val):
    return val * 0.10

def round_increased_salary(val):
    return round(val * 1.10)

def increment_exp(val):
    return val + 1

def square_val(val):
    return val ** 2

1. Increase salary by 10%.

In [115]:
display(df["Salary"].apply(add_ten_percent))

0    55000.0
1    49500.0
2    66000.0
3    60500.0
4    77000.0
5    52800.0
6    82500.0
7    71500.0
Name: Salary, dtype: float64

2. Calculate Annual Salary.

In [116]:
display(df["Salary"].apply(calc_annual))

0    600000
1    540000
2    720000
3    660000
4    840000
5    576000
6    900000
7    780000
Name: Salary, dtype: int64

3. Calculate Bonus equal to 10% of Salary.

In [117]:
display(df["Salary"].apply(calc_bonus))

0    5000.0
1    4500.0
2    6000.0
3    5500.0
4    7000.0
5    4800.0
6    7500.0
7    6500.0
Name: Salary, dtype: float64

4. Round salary values after increasing them by 10%.

In [118]:
display(df["Salary"].apply(round_increased_salary))

0    55000
1    49500
2    66000
3    60500
4    77000
5    52800
6    82500
7    71500
Name: Salary, dtype: int64

5. Add 1 year to every employee's Experience.

In [119]:
display(df["Experience"].apply(increment_exp))

0     3
1     5
2     6
3     4
4     9
5     5
6    10
7     7
Name: Experience, dtype: int64

6. Find the square of Experience values.

In [120]:
display(df["Experience"].apply(square_val))

0     4
1    16
2    25
3     9
4    64
5    16
6    81
7    36
Name: Experience, dtype: int64

##🔹 Section F: Lambda Functions

###10. Lambda Practice

In [121]:
df_lambda = df.copy()
display(df_lambda)

   Emp_ID    Name Department       City  Salary  Experience  Rating
0     101   Rahul         DS  Hyderabad   50000           2       4
1     102   Priya         HR  Bangalore   45000           4       3
2     103   Arjun         IT    Chennai   60000           5       5
3     104   Sneha    Finance     Mumbai   55000           3       4
4     105   Kiran         IT  Hyderabad   70000           8       5
5     106   Pooja         HR  Bangalore   48000           4       3
6     107  Vikram         DS    Chennai   75000           9       5
7     108  Anjali    Finance     Mumbai   65000           6       4

1. Increase salary by 10% using lambda.

In [122]:
df_lambda["Increased_Salary"] = df_lambda["Salary"].apply(lambda x: x * 1.10)
display(df_lambda)

,Emp_ID,Name,Department,City,Salary,Experience,Rating,Increased_Salary
0,101,Rahul,DS,Hyderabad,50000,2,4,55000.0
1,102,Priya,HR,Bangalore,45000,4,3,49500.0
2,103,Arjun,IT,Chennai,60000,5,5,66000.0
3,104,Sneha,Finance,Mumbai,55000,3,4,60500.0
4,105,Kiran,IT,Hyderabad,70000,8,5,77000.0
5,106,Pooja,HR,Bangalore,48000,4,3,52800.0
6,107,Vikram,DS,Chennai,75000,9,5,82500.0
7,108,Anjali,Finance,Mumbai,65000,6,4,71500.0

2. Create an Annual_Salary column using lambda.

In [123]:
df_lambda["Annual_Salary"] = df_lambda["Salary"].apply(lambda x: x * 12)
display(df_lambda)

,Emp_ID,Name,Department,City,Salary,Experience,Rating,Increased_Salary,Annual_Salary
0,101,Rahul,DS,Hyderabad,50000,2,4,55000.0,600000
1,102,Priya,HR,Bangalore,45000,4,3,49500.0,540000
2,103,Arjun,IT,Chennai,60000,5,5,66000.0,720000
3,104,Sneha,Finance,Mumbai,55000,3,4,60500.0,660000
4,105,Kiran,IT,Hyderabad,70000,8,5,77000.0,840000
5,106,Pooja,HR,Bangalore,48000,4,3,52800.0,576000
6,107,Vikram,DS,Chennai,75000,9,5,82500.0,900000
7,108,Anjali,Finance,Mumbai,65000,6,4,71500.0,780000

3. Create a Bonus column equal to 10% of Salary.

In [124]:
df_lambda["Bonus"] = df_lambda["Salary"].apply(lambda x: x * 0.10)
display(df_lambda)

,Emp_ID,Name,Department,City,Salary,Experience,Rating,Increased_Salary,Annual_Salary,Bonus
0,101,Rahul,DS,Hyderabad,50000,2,4,55000.0,600000,5000.0
1,102,Priya,HR,Bangalore,45000,4,3,49500.0,540000,4500.0
2,103,Arjun,IT,Chennai,60000,5,5,66000.0,720000,6000.0
3,104,Sneha,Finance,Mumbai,55000,3,4,60500.0,660000,5500.0
4,105,Kiran,IT,Hyderabad,70000,8,5,77000.0,840000,7000.0
5,106,Pooja,HR,Bangalore,48000,4,3,52800.0,576000,4800.0
6,107,Vikram,DS,Chennai,75000,9,5,82500.0,900000,7500.0
7,108,Anjali,Finance,Mumbai,65000,6,4,71500.0,780000,6500.0

4. Create a Tax column equal to 5% of Salary.

In [125]:
df_lambda["Tax"] = df_lambda["Salary"].apply(lambda x: x * 0.05)
display(df_lambda)

,Emp_ID,Name,Department,City,Salary,Experience,Rating,Increased_Salary,Annual_Salary,Bonus,Tax
0,101,Rahul,DS,Hyderabad,50000,2,4,55000.0,600000,5000.0,2500.0
1,102,Priya,HR,Bangalore,45000,4,3,49500.0,540000,4500.0,2250.0
2,103,Arjun,IT,Chennai,60000,5,5,66000.0,720000,6000.0,3000.0
3,104,Sneha,Finance,Mumbai,55000,3,4,60500.0,660000,5500.0,2750.0
4,105,Kiran,IT,Hyderabad,70000,8,5,77000.0,840000,7000.0,3500.0
5,106,Pooja,HR,Bangalore,48000,4,3,52800.0,576000,4800.0,2400.0
6,107,Vikram,DS,Chennai,75000,9,5,82500.0,900000,7500.0,3750.0
7,108,Anjali,Finance,Mumbai,65000,6,4,71500.0,780000,6500.0,3250.0

5. Add 1 year to every employee's Experience using lambda.

In [126]:
df_lambda["New_Experience"] = df_lambda["Experience"].apply(lambda x: x + 1)
display(df_lambda)

,Emp_ID,Name,Department,City,Salary,Experience,Rating,Increased_Salary,Annual_Salary,Bonus,Tax,New_Experience
0,101,Rahul,DS,Hyderabad,50000,2,4,55000.0,600000,5000.0,2500.0,3
1,102,Priya,HR,Bangalore,45000,4,3,49500.0,540000,4500.0,2250.0,5
2,103,Arjun,IT,Chennai,60000,5,5,66000.0,720000,6000.0,3000.0,6
3,104,Sneha,Finance,Mumbai,55000,3,4,60500.0,660000,5500.0,2750.0,4
4,105,Kiran,IT,Hyderabad,70000,8,5,77000.0,840000,7000.0,3500.0,9
5,106,Pooja,HR,Bangalore,48000,4,3,52800.0,576000,4800.0,2400.0,5
6,107,Vikram,DS,Chennai,75000,9,5,82500.0,900000,7500.0,3750.0,10
7,108,Anjali,Finance,Mumbai,65000,6,4,71500.0,780000,6500.0,3250.0,7

##🔹 Section G: Map Function

###11. Mapping Practice

In [127]:
df_map = df.copy()

dept_mapping = {
    "DS": "D01",
    "HR": "D02",
    "IT": "D03",
    "Finance": "D04"
}

city_mapping = {
    "Hyderabad": "HYD",
    "Bangalore": "BLR",
    "Chennai": "MAA",
    "Mumbai": "BOM"
}

1. Create a Department_Code column using map().

In [128]:
df_map["Department_Code"] = df_map["Department"].map(dept_mapping)
df_map

,Emp_ID,Name,Department,City,Salary,Experience,Rating,Department_Code
0,101,Rahul,DS,Hyderabad,50000,2,4,D01
1,102,Priya,HR,Bangalore,45000,4,3,D02
2,103,Arjun,IT,Chennai,60000,5,5,D03
3,104,Sneha,Finance,Mumbai,55000,3,4,D04
4,105,Kiran,IT,Hyderabad,70000,8,5,D03
5,106,Pooja,HR,Bangalore,48000,4,3,D02
6,107,Vikram,DS,Chennai,75000,9,5,D01
7,108,Anjali,Finance,Mumbai,65000,6,4,D04

2. Create a City_Code column using map().

In [129]:
df_map["City_Code"] = df_map["City"].map(city_mapping)
df_map

,Emp_ID,Name,Department,City,Salary,Experience,Rating,Department_Code,City_Code
0,101,Rahul,DS,Hyderabad,50000,2,4,D01,HYD
1,102,Priya,HR,Bangalore,45000,4,3,D02,BLR
2,103,Arjun,IT,Chennai,60000,5,5,D03,MAA
3,104,Sneha,Finance,Mumbai,55000,3,4,D04,BOM
4,105,Kiran,IT,Hyderabad,70000,8,5,D03,HYD
5,106,Pooja,HR,Bangalore,48000,4,3,D02,BLR
6,107,Vikram,DS,Chennai,75000,9,5,D01,MAA
7,108,Anjali,Finance,Mumbai,65000,6,4,D04,BOM

In [130]:
display(df_map[["Name", "Department", "Department_Code", "City", "City_Code"]])

     Name Department Department_Code       City City_Code
0   Rahul         DS             D01  Hyderabad       HYD
1   Priya         HR             D02  Bangalore       BLR
2   Arjun         IT             D03    Chennai       MAA
3   Sneha    Finance             D04     Mumbai       BOM
4   Kiran         IT             D03  Hyderabad       HYD
5   Pooja         HR             D02  Bangalore       BLR
6  Vikram         DS             D01    Chennai       MAA
7  Anjali    Finance             D04     Mumbai       BOM

##🔹 Section H: Pivot

###12. Pivot Operations

1. Create a Department vs Salary pivot table.

In [131]:
df_pivot_sal = df.pivot(index="Name", columns="Department", values="Salary")
display(df_pivot_sal)

Department       DS  Finance       HR       IT
Name
Anjali          NaN  65000.0      NaN      NaN
Arjun           NaN      NaN      NaN  60000.0
Kiran           NaN      NaN      NaN  70000.0
Pooja           NaN      NaN  48000.0      NaN
Priya           NaN      NaN  45000.0      NaN
Rahul       50000.0      NaN      NaN      NaN
Sneha           NaN  55000.0      NaN      NaN
Vikram      75000.0      NaN      NaN      NaN

2. Create a Department vs Experience pivot table.

In [132]:
df_pivot_exp = df.pivot(index="Name", columns="Department", values="Experience")
display(df_pivot_exp)

Department   DS  Finance   HR   IT
Name
Anjali      NaN      6.0  NaN  NaN
Arjun       NaN      NaN  NaN  5.0
Kiran       NaN      NaN  NaN  8.0
Pooja       NaN      NaN  4.0  NaN
Priya       NaN      NaN  4.0  NaN
Rahul       2.0      NaN  NaN  NaN
Sneha       NaN      3.0  NaN  NaN
Vikram      9.0      NaN  NaN  NaN

3. Create a City vs Salary pivot table.

In [133]:
df_pivot_city_sal = df.pivot(index="Name", columns="City", values="Salary")
display(df_pivot_city_sal)

City    Bangalore  Chennai  Hyderabad   Mumbai
Name
Anjali        NaN      NaN        NaN  65000.0
Arjun         NaN  60000.0        NaN      NaN
Kiran         NaN      NaN    70000.0      NaN
Pooja     48000.0      NaN        NaN      NaN
Priya     45000.0      NaN        NaN      NaN
Rahul         NaN      NaN    50000.0      NaN
Sneha         NaN      NaN        NaN  55000.0
Vikram        NaN  75000.0        NaN      NaN

##🔹 Section I: Pivot Table

###13. Pivot Table Operations

1. Calculate average salary by Department.

In [134]:
display(df.pivot_table(index="Department", values="Salary", aggfunc="mean"))

             Salary
Department
DS          62500.0
Finance     60000.0
HR          46500.0
IT          65000.0

2. Calculate total salary by Department.

In [135]:
display(df.pivot_table(index="Department", values="Salary", aggfunc="sum"))

            Salary
Department
DS          125000
Finance     120000
HR           93000
IT          130000

3. Calculate average salary by Department and City.

In [136]:
display(df.pivot_table(index="Department", columns="City", values="Salary", aggfunc="mean"))

City        Bangalore  Chennai  Hyderabad   Mumbai
Department
DS                NaN  75000.0    50000.0      NaN
Finance           NaN      NaN        NaN  60000.0
HR            46500.0      NaN        NaN      NaN
IT                NaN  60000.0    70000.0      NaN

4. Calculate total salary by Department and City.

In [137]:
display(df.pivot_table(index="Department", columns="City", values="Salary", aggfunc="sum", fill_value=0))

City        Bangalore  Chennai  Hyderabad  Mumbai
Department
DS                  0    75000      50000       0
Finance             0        0          0  120000
HR              93000        0          0       0
IT                  0    60000      70000       0