Filtering

In [1]:
import numpy as np
import pandas as pd

In [2]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# get elements [1, 3, 5, 6, 9, 10]
arr[[0, 2, 4, 5, 8, 9]]

array([ 1,  3,  5,  6,  9, 10])

In [4]:
arr[np.array([0, 2, 4, 5, 8, 9])]

array([ 1,  3,  5,  6,  9, 10])

In [6]:
# get elements [1, 3, 5, 6, 9, 10] using bOOLENS
arr[[True, False, True, False, True, True, False, False, True, True]]

array([ 1,  3,  5,  6,  9, 10])

In [9]:
# series
ser = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9,10])
ser

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [10]:
# Apply boolean indexing and get even elements - TEDIOUS
ser[[False, True, False, True, False, True, False, True, False, True]]

1     2
3     4
5     6
7     8
9    10
dtype: int64

In [11]:
ser%2 == 0

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7     True
8    False
9     True
dtype: bool

In [12]:
ser.iloc[ser%2 == 0]

NotImplementedError: iLocation based boolean indexing on an integer type is not available

In [13]:
ser.loc[ser%2 == 0]

1     2
3     4
5     6
7     8
9    10
dtype: int64

In [15]:
ser1 = pd.Series(np.random.randint(1, 11, 10,))
ser1

0     5
1     2
2     8
3     5
4    10
5     5
6     1
7     4
8     7
9     1
dtype: int64

In [17]:
# get the elements divisible by 3
ser%3 == 0

0    False
1    False
2     True
3    False
4    False
5     True
6    False
7    False
8     True
9    False
dtype: bool

In [16]:
ser.loc[ser%3 == 0]

2    3
5    6
8    9
dtype: int64

In [18]:
ser.iloc[ser%3 == 0] #

NotImplementedError: iLocation based boolean indexing on an integer type is not available

In [19]:
ser

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [20]:
# get elements divisble by 2 and 3
ser%2 == 0 and ser%3 == 0

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

To combine multiple conditions
1. Enclose every condition in a parenthesis
2. Don't use `and`, `or` always use `&`, `|`

In [24]:
(ser%2 == 0) & (ser%3 == 0)

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
8    False
9    False
dtype: bool

In [25]:
ser[(ser%2 ==0) & (ser%3 == 0)]

5    6
dtype: int64

Filtering: Dataframe

In [26]:
arr = np.arange(1, 21).reshape(4, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [27]:
df = pd.DataFrame(arr)
df

    0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20

In [28]:
df = pd.DataFrame(arr, index=['r1', 'r2', 'r3', 'r4'])
df

     0   1   2   3   4
r1   1   2   3   4   5
r2   6   7   8   9  10
r3  11  12  13  14  15
r4  16  17  18  19  20

In [29]:
df = pd.DataFrame(arr, index=['r1', 'r2', 'r3', 'r4'], columns=['c1', 'c2', 'c3', 'c4', 'c5'])
df

    c1  c2  c3  c4  c5
r1   1   2   3   4   5
r2   6   7   8   9  10
r3  11  12  13  14  15
r4  16  17  18  19  20

By applying a condition on an column
- Get Booleans on rows
- Filter the rows of a datafram

In [30]:
# Filter column c1 with `>6`
#df['c1'] or df.c1
df['c1'] > 6

r1    False
r2    False
r3     True
r4     True
Name: c1, dtype: bool

In [31]:
df.loc[df['c1'] > 6]

    c1  c2  c3  c4  c5
r3  11  12  13  14  15
r4  16  17  18  19  20

In [32]:
# On col 'c2' condition - %2 == 0
df['c2']%2 == 0

r1     True
r2    False
r3     True
r4    False
Name: c2, dtype: bool

In [33]:
df[df['c2']%2 == 0]

    c1  c2  c3  c4  c5
r1   1   2   3   4   5
r3  11  12  13  14  15

In [34]:
# Filter the elements of column 'c4' either divisible by 2 or divisible by 3
(df.c4%2 == 0) | (df.c4%3 == 0)

r1     True
r2     True
r3     True
r4    False
Name: c4, dtype: bool

In [35]:
df[(df.c4%2 == 0) | (df.c4%3 == 0)]

    c1  c2  c3  c4  c5
r1   1   2   3   4   5
r2   6   7   8   9  10
r3  11  12  13  14  15

In [37]:
# Get the Negation of aove result (use tilde)
df[~((df.c4%2 == 0) | (df.c4%3 == 0))]

    c1  c2  c3  c4  c5
r4  16  17  18  19  20

In [38]:
~((df.c4%2 == 0) | (df.c4%3 == 0))

r1    False
r2    False
r3    False
r4     True
Name: c4, dtype: bool

In [39]:
df

    c1  c2  c3  c4  c5
r1   1   2   3   4   5
r2   6   7   8   9  10
r3  11  12  13  14  15
r4  16  17  18  19  20

In [43]:
~((df.c5%5 == 0) & (df.c5%10 == 0))

r1     True
r2    False
r3     True
r4    False
Name: c5, dtype: bool

In [44]:
df[~((df.c5%5 == 0) & (df.c5%10 == 0))]

    c1  c2  c3  c4  c5
r1   1   2   3   4   5
r3  11  12  13  14  15

In [45]:
# get only columns c2 and c4
# Traditional way - NOT RECOMMENDED - chaining
df[~((df.c5%5 == 0) & (df.c5%10 == 0))][['c2', 'c4']]

    c2  c4
r1   2   4
r3  12  14

df.loc[rI/RRange/Rlist/**RBool**, cI/Crange/**clist**/cBool]
- Apply a condition on columns
  - returns Row Bool

In [46]:
df.loc[~((df.c5%5 == 0) & (df.c5%10 == 0)), ['c2', 'c4']]

    c2  c4
r1   2   4
r3  12  14

In [47]:
df

    c1  c2  c3  c4  c5
r1   1   2   3   4   5
r2   6   7   8   9  10
r3  11  12  13  14  15
r4  16  17  18  19  20

Filter the dataframe using c3 elements which are divisible either 3 or 6 and get the columns c1, c3, c5

In [52]:
df.loc[((df.c3%3 == 0) | (df.c3%6 == 0)), ['c1','c3', 'c5']]

    c1  c3  c5
r1   1   3   5
r4  16  18  20

In [53]:
(df.c3%3 == 0) | (df.c3%6 == 0)

r1     True
r2    False
r3    False
r4     True
Name: c3, dtype: bool

df.loc[rI/RRange/Rlist/**RBool**, cI/Crange/**clist**/cBool]

In [54]:
df.loc[(df['c3']%3 == 0) | (df['c3']%6 == 0)]

    c1  c2  c3  c4  c5
r1   1   2   3   4   5
r4  16  17  18  19  20

In [55]:
# traditional - Not recommended
df[(df['c3']%3 == 0) | (df['c3']%6 == 0)][['c1', 'c3', 'c5']]

    c1  c3  c5
r1   1   3   5
r4  16  18  20

In [ ]:
#recommended

In [56]:
df

    c1  c2  c3  c4  c5
r1   1   2   3   4   5
r2   6   7   8   9  10
r3  11  12  13  14  15
r4  16  17  18  19  20

Filter the dataframe on c4, in which the elements of c4 neither divisible by 2 nor divisible by 3. Get info of columns c1 and c5

In [57]:
(df['c4']%2 == 0) | (df['c4']%3 == 0)

r1     True
r2     True
r3     True
r4    False
Name: c4, dtype: bool

In [70]:
~((df['c4']%2 == 0) | (df['c4']%3 == 0))

r1    False
r2    False
r3    False
r4     True
Name: c4, dtype: bool

In [71]:
df.loc[~((df['c4']%2 == 0) | (df['c4']%3 == 0))]

    c1  c2  c3  c4  c5
r4  16  17  18  19  20

In [74]:
df.loc[~((df['c4']%2 == 0) | (df['c4']%3 == 0))][['c1', 'c5']]

    c1  c5
r4  16  20

In [75]:
df.loc[~((df.c4%2 == 0) | (df.c4%3 == 0)), ['c1', 'c5']]

    c1  c5
r4  16  20

In [76]:
df

    c1  c2  c3  c4  c5
r1   1   2   3   4   5
r2   6   7   8   9  10
r3  11  12  13  14  15
r4  16  17  18  19  20

Filter df based on r1 with elements lessthan 3

In [77]:
df['r1']

KeyError: 'r1'

In [78]:
df.loc['r1', :]

c1    1
c2    2
c3    3
c4    4
c5    5
Name: r1, dtype: int64

In [79]:
df.loc['r1', :] < 3

c1     True
c2     True
c3    False
c4    False
c5    False
Name: r1, dtype: bool

df.loc[rI/rRange/rlist/rBool, cI/cRange/cList/cBool]

In [80]:
df.loc[:,df.loc['r1', :] < 3]

    c1  c2
r1   1   2
r2   6   7
r3  11  12
r4  16  17

In [81]:
df

    c1  c2  c3  c4  c5
r1   1   2   3   4   5
r2   6   7   8   9  10
r3  11  12  13  14  15
r4  16  17  18  19  20

Filter df based on c3 with elements greaterthan 12 and get the information about r1, r3

In [99]:
df.loc[:, df.loc['r3', :] > 12]

    c3  c4  c5
r1   3   4   5
r2   8   9  10
r3  13  14  15
r4  18  19  20

In [101]:
df.loc[['r1', 'r3'], df.loc['r3', :] > 12]

    c3  c4  c5
r1   3   4   5
r3  13  14  15

`object` datatype

In [102]:
ser = pd.Series([1, 2, 3, True, 'hello'])
ser

0        1
1        2
2        3
3     True
4    hello
dtype: object

In [103]:
ser + ser

0             2
1             4
2             6
3             2
4    hellohello
dtype: object